# Generated by Django 4.0.5 on 2022-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата публикации')),
                ('text', models.TextField(verbose_name='ело новости')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
            ],
        ),
    ]
