# Generated by Django 4.0.5 on 2022-06-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='картинка'),
        ),
    ]
