# Generated by Django 4.0.5 on 2022-06-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='тело новости'),
        ),
    ]
